export type FruitType = "Zoan" | "Paramecia" | "Logia";
export type FruitRarity = "Comum" | "Ancestral" | "Mítica" | "Criação";

export interface AkumaNoMi {
  id: string;
  name: string;
  type: FruitType;
  rarity: FruitRarity;
  description: string;
  baseDamage: string;
  passiveEffect: string;
  vigorBonus?: number;
  agilityBonus?: number;
  cunningBonus?: number;
  spiritBonus?: number;
}

export const AKUMA_NO_MI: AkumaNoMi[] = [
  // ─── ZOAN COMUM ───────────────────────────────────────────────
  {
    id: "neko-leopardo",
    name: "Neko Neko no Mi: Modelo Leopardo",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em leopardo. Utilizado por Rob Lucci.",
    baseDamage: "1d12",
    passiveEffect: "Forma Híbrida: +2 Vigor e +2 Agilidade.",
    vigorBonus: 2,
    agilityBonus: 2,
  },
  {
    id: "inu-lobo",
    name: "Inu Inu no Mi: Modelo Lobo",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em lobo selvagem.",
    baseDamage: "1d10",
    passiveEffect: "+1 Vigor, +1 Agilidade.",
    vigorBonus: 1,
    agilityBonus: 1,
  },
  {
    id: "ushi-bufalo",
    name: "Ushi Ushi no Mi: Modelo Búfalo",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em búfalo. Carga devastadora.",
    baseDamage: "1d10",
    passiveEffect: "+3 Vigor, -1 Agilidade. Ataque especial: Charge.",
    vigorBonus: 3,
    agilityBonus: -1,
  },
  {
    id: "ori-gorila",
    name: "Ori Ori no Mi: Modelo Gorila das Montanhas",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em gorila gigante.",
    baseDamage: "1d12",
    passiveEffect: "+3 Vigor. Ataque especial: Pancada.",
    vigorBonus: 3,
  },
  {
    id: "uma-cavalo",
    name: "Uma Uma no Mi: Modelo Cavalo Selvagem",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em cavalo selvagem. Velocidade duplicada.",
    baseDamage: "1d8",
    passiveEffect: "+2 Agilidade. Movimento dobrado.",
    agilityBonus: 2,
  },
  {
    id: "mogu-toupeira",
    name: "Mogu Mogu no Mi: Modelo Toupeira Gigante",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em toupeira. Capacidade de escavar túneis.",
    baseDamage: "1d6",
    passiveEffect: "Escavar túneis. Vantagem em furtividade subterrânea.",
  },
  {
    id: "hebi-anaconda",
    name: "Hebi Hebi no Mi: Modelo Anaconda",
    type: "Zoan",
    rarity: "Comum",
    description: "Transforma em anaconda gigante.",
    baseDamage: "1d10",
    passiveEffect: "+2 Vigor. Habilidade de constrição.",
    vigorBonus: 2,
  },

  // ─── ZOAN ANCESTRAL ───────────────────────────────────────────
  {
    id: "ryu-tiranossauro",
    name: "Ryu Ryu no Mi: Modelo Tiranossauro",
    type: "Zoan",
    rarity: "Ancestral",
    description: "Transforma em Tiranossauro. Utilizado por Drake.",
    baseDamage: "1d20",
    passiveEffect: "+4 Vigor, -2 Agilidade.",
    vigorBonus: 4,
    agilityBonus: -2,
  },
  {
    id: "zou-mamute",
    name: "Zou Zou no Mi: Modelo Mamute",
    type: "Zoan",
    rarity: "Ancestral",
    description: "Transforma em mamute ancestral.",
    baseDamage: "1d20",
    passiveEffect: "+5 Vigor, -3 Agilidade.",
    vigorBonus: 5,
    agilityBonus: -3,
  },
  {
    id: "kuma-urso-cavernas",
    name: "Kuma Kuma no Mi: Modelo Urso das Cavernas",
    type: "Zoan",
    rarity: "Ancestral",
    description: "Transforma em urso das cavernas ancestral.",
    baseDamage: "1d12",
    passiveEffect: "+4 Vigor. Ataque especial: Patada.",
    vigorBonus: 4,
  },

  // ─── ZOAN MÍTICA ──────────────────────────────────────────────
  {
    id: "tori-fenix",
    name: "Tori Tori no Mi: Modelo Fênix",
    type: "Zoan",
    rarity: "Mítica",
    description: "Transforma em Fênix. Utilizado por Marco. Regeneração passiva.",
    baseDamage: "1d10",
    passiveEffect: "Regeneração: Recupera 1d10 de vida por turno. +2 Agilidade.",
    agilityBonus: 2,
  },
  {
    id: "inu-okami",
    name: "Inu Inu no Mi: Modelo Okami (Lobo Divino)",
    type: "Zoan",
    rarity: "Mítica",
    description: "Transforma em lobo divino. Criação.",
    baseDamage: "1d12",
    passiveEffect: "+3 Agilidade, +3 Espírito. Cria barreiras de vento.",
    agilityBonus: 3,
    spiritBonus: 3,
  },
  {
    id: "zou-ganesha",
    name: "Zou Zou no Mi: Modelo Ganesha",
    type: "Zoan",
    rarity: "Mítica",
    description: "Transforma em Ganesha divino. Manipula gravidade em área.",
    baseDamage: "1d20",
    passiveEffect: "+4 Vigor, +3 Espírito. Controle de grupo por gravidade.",
    vigorBonus: 4,
    spiritBonus: 3,
  },

  // ─── PARAMECIA — CORPO ────────────────────────────────────────
  {
    id: "gomu-gomu",
    name: "Gomu Gomu no Mi (Hito Hito no Mi: Modelo Nika)",
    type: "Paramecia",
    rarity: "Mítica",
    description: "Corpo de borracha. Utilizado por Luffy.",
    baseDamage: "1d12",
    passiveEffect: "Resistência a dano físico e elétrico. Vulnerável a cortes.",
  },
  {
    id: "hana-hana",
    name: "Hana Hana no Mi",
    type: "Paramecia",
    rarity: "Comum",
    description: "Brota membros em qualquer lugar. Utilizado por Robin.",
    baseDamage: "1d8",
    passiveEffect: "Astúcia para testes de Agilidade à distância.",
    cunningBonus: 1,
  },
  {
    id: "nika-nika",
    name: "Nika Nika no Mi: Fruta do Sorriso",
    type: "Paramecia",
    rarity: "Criação",
    description: "Corpo elástico sem a passiva de borracha.",
    baseDamage: "1d10",
    passiveEffect: "Elasticidade normal. Resistência padrão.",
  },
  {
    id: "dura-dura",
    name: "Dura Dura no Mi: Fruta do Endurecimento",
    type: "Paramecia",
    rarity: "Criação",
    description: "Corpo de metal/diamante.",
    baseDamage: "1d12",
    passiveEffect: "Alta resistência a dano. -1 Agilidade.",
    agilityBonus: -1,
  },
  {
    id: "kachi-kachi",
    name: "Kachi Kachi no Mi: Fruta do Calor/Peso",
    type: "Paramecia",
    rarity: "Criação",
    description: "Aumenta o peso e calor do corpo.",
    baseDamage: "1d10",
    passiveEffect: "+2 Vigor. Impede movimento do oponente.",
    vigorBonus: 2,
  },
  {
    id: "mira-mira",
    name: "Mira Mira no Mi: Fruta do Espelho",
    type: "Paramecia",
    rarity: "Criação",
    description: "Cria espelhos que refletem ataques.",
    baseDamage: "1d8",
    passiveEffect: "Espírito para defesa. Mundo paralelo dos espelhos.",
    spiritBonus: 1,
  },

  // ─── PARAMECIA — AMBIENTE ─────────────────────────────────────
  {
    id: "gura-gura",
    name: "Gura Gura no Mi",
    type: "Paramecia",
    rarity: "Mítica",
    description: "Cria terremotos. Utilizado por Barba Branca.",
    baseDamage: "1d12",
    passiveEffect: "Golpe Terremoto: 1d20+Espírito em área, ignora 50% defesa.",
    spiritBonus: 2,
  },
  {
    id: "zushi-zushi",
    name: "Zushi Zushi no Mi: Fruta da Gravidade",
    type: "Paramecia",
    rarity: "Criação",
    description: "Manipula gravidade em área. Utilizado por Fujitora.",
    baseDamage: "1d10",
    passiveEffect: "Espírito para controle de grupo. -Agilidade dos inimigos.",
    spiritBonus: 1,
  },
  {
    id: "hie-hie-param",
    name: "Hie Hie no Mi: Modelo Gelo (Paramecia)",
    type: "Paramecia",
    rarity: "Criação",
    description: "Cria e manipula gelo, sem intangibilidade.",
    baseDamage: "1d10",
    passiveEffect: "Pode ser ferido normalmente.",
  },
  {
    id: "suna-suna-param",
    name: "Suna Suna no Mi: Modelo Areia (Paramecia)",
    type: "Paramecia",
    rarity: "Criação",
    description: "Cria e manipula areia, sem intangibilidade.",
    baseDamage: "1d8",
    passiveEffect: "Pode ser ferido normalmente. Desidratação.",
  },
  {
    id: "ato-ato",
    name: "Ato Ato no Mi",
    type: "Paramecia",
    rarity: "Comum",
    description: "Transforma o ambiente em obras de arte. Utilizado por Giolla.",
    baseDamage: "1d6",
    passiveEffect: "Astúcia para controle de grupo.",
    cunningBonus: 1,
  },
  {
    id: "uta-uta",
    name: "Uta Uta no Mi",
    type: "Paramecia",
    rarity: "Mítica",
    description: "Cria um mundo paralelo através do som. Utilizado por Uta.",
    baseDamage: "1d8",
    passiveEffect: "Espírito para controle de grupo e ilusões.",
    spiritBonus: 2,
  },
  {
    id: "kuma-kuma-param",
    name: "Kuma Kuma no Mi: Modelo Urso (Paramecia)",
    type: "Paramecia",
    rarity: "Criação",
    description: "Patas de urso que podem puxar/empurrar tudo.",
    baseDamage: "1d10",
    passiveEffect: "Repele tudo ao alcance.",
  },
  {
    id: "nikyu-nikyu",
    name: "Nikyu Nikyu no Mi",
    type: "Paramecia",
    rarity: "Comum",
    description: "Patas de urso que repelem tudo. Utilizado por Kuma.",
    baseDamage: "1d10",
    passiveEffect: "Dano 1d10+Vigor. Repulsa 2d20 metros.",
    vigorBonus: 1,
  },

  // ─── LOGIA CLÁSSICA ───────────────────────────────────────────
  {
    id: "mera-mera",
    name: "Mera Mera no Mi",
    type: "Logia",
    rarity: "Comum",
    description: "Fogo. Utilizado por Ace e Sabo.",
    baseDamage: "1d12",
    passiveEffect: "Intangibilidade: Imune a dano não-Haki. +3 Espírito.",
    spiritBonus: 3,
  },
  {
    id: "goro-goro",
    name: "Goro Goro no Mi",
    type: "Logia",
    rarity: "Comum",
    description: "Eletricidade. Utilizado por Enel.",
    baseDamage: "1d12",
    passiveEffect: "Relâmpago: 1d20+Espírito, ignora 50% defesa. +3 Espírito.",
    spiritBonus: 3,
  },
  {
    id: "yami-yami",
    name: "Yami Yami no Mi",
    type: "Logia",
    rarity: "Mítica",
    description: "Escuridão. Utilizado por Barba Negra.",
    baseDamage: "1d12",
    passiveEffect: "Negação de Akuma no Mi: Anula poderes de outras frutas ao toque. +3 Espírito.",
    spiritBonus: 3,
  },
  {
    id: "pika-pika",
    name: "Pika Pika no Mi",
    type: "Logia",
    rarity: "Mítica",
    description: "Luz. Utilizado por Kizaru. Velocidade da luz.",
    baseDamage: "1d12",
    passiveEffect: "+4 Agilidade. Intangibilidade de Luz.",
    agilityBonus: 4,
    spiritBonus: 2,
  },
  {
    id: "magu-magu",
    name: "Magu Magu no Mi",
    type: "Logia",
    rarity: "Mítica",
    description: "Magma. Utilizado por Akainu.",
    baseDamage: "1d12",
    passiveEffect: "Magma: 1d20+Espírito em área, ignora 50% defesa. +3 Espírito.",
    spiritBonus: 3,
  },
  {
    id: "hie-hie-logia",
    name: "Hie Hie no Mi: Modelo Gelo (Logia)",
    type: "Logia",
    rarity: "Comum",
    description: "Gelo. Utilizado por Aokiji.",
    baseDamage: "1d12",
    passiveEffect: "Intangibilidade de Gelo. +3 Espírito.",
    spiritBonus: 3,
  },
  {
    id: "zushi-zushi-logia",
    name: "Zushi Zushi no Mi: Modelo Gravidade (Logia)",
    type: "Logia",
    rarity: "Criação",
    description: "Gravidade com intangibilidade. Utilizado por Fujitora.",
    baseDamage: "1d10",
    passiveEffect: "Intangibilidade de Gravidade. Dano de área.",
    spiritBonus: 2,
  },

  // ─── LOGIA CRIADA ─────────────────────────────────────────────
  {
    id: "tori-relampago",
    name: "Tori Tori no Mi: Modelo Relâmpago",
    type: "Logia",
    rarity: "Criação",
    description: "Forma de ave elétrica.",
    baseDamage: "1d12",
    passiveEffect: "+4 Agilidade, +3 Espírito. Intangibilidade Elétrica.",
    agilityBonus: 4,
    spiritBonus: 3,
  },
  {
    id: "nika-nika-logia",
    name: "Nika Nika no Mi: Logia da Elasticidade",
    type: "Logia",
    rarity: "Criação",
    description: "Corpo elástico com intangibilidade.",
    baseDamage: "1d10",
    passiveEffect: "Imune a dano físico e elétrico.",
  },
  {
    id: "dura-dura-logia",
    name: "Dura Dura no Mi: Logia do Endurecimento",
    type: "Logia",
    rarity: "Criação",
    description: "Corpo de metal com intangibilidade.",
    baseDamage: "1d12",
    passiveEffect: "Imune a dano não-Haki.",
  },
  {
    id: "kachi-kachi-logia",
    name: "Kachi Kachi no Mi: Logia do Calor",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula calor com intangibilidade.",
    baseDamage: "1d10",
    passiveEffect: "+2 Vigor, +3 Espírito, +3 Agilidade.",
    vigorBonus: 2,
    agilityBonus: 3,
    spiritBonus: 3,
  },
  {
    id: "mira-mira-logia",
    name: "Mira Mira no Mi: Logia do Espelho",
    type: "Logia",
    rarity: "Criação",
    description: "Espelhos com intangibilidade.",
    baseDamage: "1d8",
    passiveEffect: "Reflete ataques. Intangibilidade de espelho.",
    spiritBonus: 2,
  },
  {
    id: "haki-haki",
    name: "Haki Haki no Mi",
    type: "Logia",
    rarity: "Mítica",
    description: "Concede todos os tipos de Haki com 100% de maestria.",
    baseDamage: "1d12",
    passiveEffect: "Armamento, Observação e Conquistador com maestria total.",
    spiritBonus: 4,
  },
  {
    id: "kaikai",
    name: "KaiKai no Mi: Fruta do Mar",
    type: "Logia",
    rarity: "Criação",
    description: "Manipulação de água. Nada em qualquer lugar.",
    baseDamage: "1d12",
    passiveEffect: "Imune à Fraqueza do Mar. Manipula correntes.",
  },
  {
    id: "sesei",
    name: "SeiSei no Mi: Fruta do Sangue",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula sangue em área.",
    baseDamage: "1d10",
    passiveEffect: "Astúcia para controle de grupo.",
    cunningBonus: 2,
  },
  {
    id: "shishi",
    name: "ShiShi no Mi: Fruta da Morte",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula a morte em área.",
    baseDamage: "1d12",
    passiveEffect: "Dano 1d20+Espírito, ignora 50% defesa.",
    spiritBonus: 3,
  },
  {
    id: "kiki",
    name: "KiKi no Mi: Fruta da Vida",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula a vida em área.",
    baseDamage: "1d10",
    passiveEffect: "Cura 1d20 de vida, +2 Vigor.",
    vigorBonus: 2,
  },
  {
    id: "tenten",
    name: "TenTen no Mi: Fruta do Céu",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula o céu em área. Capacidade de voo.",
    baseDamage: "1d10",
    passiveEffect: "Voo. Controle de grupo.",
    cunningBonus: 1,
  },
  {
    id: "jiji",
    name: "JiJi no Mi: Fruta do Tempo",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula o tempo em área.",
    baseDamage: "1d12",
    passiveEffect: "Controle de grupo e +Agilidade temporário.",
    agilityBonus: 2,
    cunningBonus: 2,
  },
  {
    id: "spacespace",
    name: "SpaceSpace no Mi: Fruta do Espaço",
    type: "Logia",
    rarity: "Criação",
    description: "Manipula o espaço. Teletransporte.",
    baseDamage: "1d12",
    passiveEffect: "Teletransporte em área. Controle de grupo.",
    cunningBonus: 2,
  },
  {
    id: "godgod",
    name: "GodGod no Mi: Fruta de Deus",
    type: "Logia",
    rarity: "Mítica",
    description: "Poderes divinos. Criação de milagres.",
    baseDamage: "1d20",
    passiveEffect: "Manipulação divina total.",
    spiritBonus: 5,
  },
  {
    id: "devildevil",
    name: "DevilDevil no Mi: Fruta do Diabo",
    type: "Logia",
    rarity: "Mítica",
    description: "Poderes demoníacos. Criação de pragas.",
    baseDamage: "1d20",
    passiveEffect: "Manipulação demoníaca total.",
    spiritBonus: 4,
    cunningBonus: 2,
  },
  {
    id: "allall",
    name: "AllAll no Mi: Fruta de Tudo",
    type: "Logia",
    rarity: "Mítica",
    description: "Manipulação total de tudo.",
    baseDamage: "1d20",
    passiveEffect: "Todos os poderes. Maestria absoluta.",
    vigorBonus: 2,
    agilityBonus: 2,
    spiritBonus: 5,
    cunningBonus: 2,
  },
];

export const FRUIT_TYPE_COLORS: Record<FruitType, { bg: string; border: string; text: string; badge: string }> = {
  Zoan:     { bg: "bg-orange-950/20",  border: "border-orange-700/50", text: "text-orange-400",  badge: "bg-orange-950/40 border-orange-700/40 text-orange-300" },
  Paramecia:{ bg: "bg-purple-950/20", border: "border-purple-700/50",  text: "text-purple-400", badge: "bg-purple-950/40 border-purple-700/40 text-purple-300" },
  Logia:    { bg: "bg-sky-950/20",    border: "border-sky-700/50",     text: "text-sky-400",    badge: "bg-sky-950/40 border-sky-700/40 text-sky-300" },
};

export const HAKI_LIST = [
  {
    id: "armamento",
    name: "Haki de Armamento",
    subtitle: "Busoshoku",
    icon: "🛡️",
    description: "Envolve o corpo com armadura invisible. Permite ferir usuários de Logia.",
    bonus: "+1d6 de dano em ataques físicos. Permite ferir Logias.",
    staminaCost: 5,
    color: "border-gray-600/60 bg-gray-950/20",
    activeColor: "border-gray-400/80 bg-gray-800/30",
    textColor: "text-gray-300",
  },
  {
    id: "observacao",
    name: "Haki de Observação",
    subtitle: "Kenbunshoku",
    icon: "👁️",
    description: "Permite sentir presença e prever movimentos dos oponentes.",
    bonus: "+4 em Esquiva/Agilidade. Permite Prever Movimentos.",
    staminaCost: 5,
    color: "border-blue-700/60 bg-blue-950/20",
    activeColor: "border-blue-400/80 bg-blue-900/30",
    textColor: "text-blue-300",
  },
  {
    id: "haoshoku",
    name: "Haki do Conquistador",
    subtitle: "Haoshoku",
    icon: "👑",
    description: "Poder raro de reis. Impõe sua vontade sobre os mais fracos.",
    bonus: "Impor Presença: Teste Espírito vs Vigor para desmaiar inimigos.",
    staminaCost: 50,
    color: "border-yellow-700/60 bg-yellow-950/20",
    activeColor: "border-yellow-400/80 bg-yellow-900/30",
    textColor: "text-yellow-300",
  },
] as const;

export type HakiId = "armamento" | "observacao" | "haoshoku";
